---
title: "p8105_hw6_kg3006"
author: "Kevin Guzman"
date: "2025-11-25"
output: github_document
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Loading appropriate libraries 
library(tidyverse)
```

## Problem 1

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Loading library from github website 
homicides <- read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")

#Creating city, state variable using "city", "state" 
homicides <- homicides %>%
  mutate(city_state = paste(city, state, sep = ", ")) %>% 
  #Creating binary variable (solved v. not solved) from disposition column
  mutate(solved = ifelse(disposition == "Closed by arrest", 1, 0)) %>% 
  #Omiting city_states Dallas, Tx, Phoenix, AZ, and Kansas City, MO for not reporting race 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO"))) %>% 
  #Omitting Tulsa, AL (entery mistake) 
  filter(city_state != "Tulsa, AL") %>% 
  #Only keeping those who are black or white race in victim_race
  filter(victim_race==c("Black", "White")) %>% 
  #Changing age to nmeric 
  mutate(victim_age = as.numeric(victim_age)) 


#Baltiomore Analysis 
  #Filtering for Baltimore, MD to new dataset
  baltimore_homicides <- homicides %>%
    filter(city_state == "Baltimore, MD")
  
  #Logistic regression model predicting whether homicide is solved based on victim age, sex, and race as predictors 
  baltimore_glm <- glm(solved ~ victim_age + victim_sex + victim_race, 
                      data = baltimore_homicides,
                      family=binomial)
  #Saving as an R object 
  saveRDS(baltimore_glm, "Output/baltimore_glm.rds")
  
  #Getting adjusted odds ratios 
  baltimore_glm %>% 
    broom::tidy(exponentiate = TRUE, conf.int = TRUE)
    
```

